name: Auto PR from Feature Branch

on:
  push:
    branches:
      - 'feature-branch'  # Replace with your desired branch name

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug GitHub Context
        run: echo "Branch: ${{ github.ref }}"

      - name: Create Pull Request
        run: |
          gh pr create --base master --head feature-branch --title "Auto PR from feature-branch" --body "This PR is automatically created from \`feature-branch\` to master."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
